
---
- block:
    - name: Update all yum packages - RHEL/CentOS
      ansible.builtin.yum:
        name: "*"
        state: latest
      register: yum_update

    - name: Check if reboot required after kernel update on CentOS/RedHat servers
      ansible.builtin.shell: KERNEL_NEW=$(rpm -q --last kernel |head -1 | awk '{print $1}' | sed 's/kernel-//'); KERNEL_NOW=$(uname -r); if [[ $KERNEL_NEW != $KERNEL_NOW ]]; then echo "reboot_needed"; else echo "reboot_not_needed"; fi
      ignore_errors: true
      register: reboot_required

    - name: 
      debug:
      msg: "{{ reboot_required }}"

    - name: Reboot CentOS/RedHat systems if kernel updated
      ansible.builtin.command: shutdown -r +1  "Rebooting CentOS/RedHat Servers After Kernel Patching"
      async: 0
      poll: 0
      when: reboot_required.stdout == "reboot_needed"
      register: reboot_started
      ignore_errors: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Rocky' or ansible_distribution == 'Amazon'

- block:
    - name: Update Ubuntu/Debian servers
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
        name: "*"
        state: latest
      register: apt_update

    - name: Check if a reboot is required after kernel update on Ubuntu/Debian servers
      ansible.builtin.stat: path=/var/run/reboot-required get_md5=no
      register: reboot_required_file

    - name: 
      debug:
      msg: "{{ rreboot_required_file }}"

    - name: Reboot Ubuntu/Debian Servers if kernel updated
      ansible.builtin.reboot:
        msg: "Rebooting Ubuntu/Debian Servers After Kernel Patching"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stdout == "reboot_needed"
      register: reboot_started_ubuntu
      ignore_errors: true
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Wait for system to become reachable
  ansible.builtin.wait_for_connection:
    timeout: 900
